### ISSUE TITLE
NO route for /oauth2/access_token

### ISSUE THREAD

**Issue by pjammer** [socialcast/devise_oauth2_providable#1]
I keep getting this error and rake routes does not have a route for it either:

```

Started POST "/oauth2/access_token" for 127.0.0.1 at 2011-05-09 13:47:07 -0400

ActionController::RoutingError (No route matches "/oauth2/access_token"):
```

I know I can just add one, but your documentation said it should be accepted somehow... Where can i look to see what I'm doing wrong?

**Comment by wireframe** [comment]
you should be using the /oauth2/token path to request access tokens.  where do you see /oauth2/access_token referenced?  i'll update any docs if they are out of date.

the only 3 supported routes today are:
GET /oauth2/authorize
POST /oauth2/authorizations
POST /oauth2/token

**Comment by pjammer** [comment]
sorry, when i am creating my omniauth provider, it defaulted to /oauth/access_token.

What are you using as your consumer app, btw?  omniauth uses OAuth2, and it's like on v10 max.  They still pass the 

``` ruby
Started GET "/profile_info.json?oauth_token=kVUTbViYOWuyXyxRQH9Tvw%3D%3D"
```

instead of just as the authorization header. that changed between 10 and 15, iirc.

So i ask what are you using for consumer side/client side as far as a gem that works with v15?
