### ISSUE TITLE
Is there a CRUD for creating Clients?

### ISSUE THREAD

**Issue by velles** [socialcast/devise_oauth2_providable#11]
I see the Client model , but not a CRUD for creating a Client. 
Is this a ToDo. I will be happy to create it and contribute to the project.
Just wanna check that I'm on the right page.

**Comment by wireframe** [comment]
contributions would be absolutely welcome!

On Fri, Aug 5, 2011 at 5:28 PM, velles <
reply@reply.github.com>wrote:

> I see the Client model , but not a CRUD for creating a Client.
> Is this ToBeDone. I will be happy to create it and contribute to the
> project.
> Just wanna check that I'm on the right page.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/socialcast/devise_oauth2_providable/issues/11

## 
- Ryan Sonnek
- twitter: twitter.com/wireframe6464
- phone: 949.351.7290
