### ISSUE TITLE
invalid_grant when I don't want grants

### ISSUE THREAD

**Issue by davestone** [socialcast/devise_oauth2_providable#16]
Sorry that this is a little spammy, but could you guys take a look at this StackOverflow post?

http://stackoverflow.com/q/7663339/124378

It's hard for me to tell if this is bug or implementation fail, but I am pretty sure its a conflict with omniauth stuff, database not saving or oauth2 expecting this to be following a newer draft of the spec than actually is.

**Comment by philsturgeon** [comment]
Hey I'm getting this too, any ideas?

**Comment by ZenCocoon** [comment]
This issue looks to be resolved at https://github.com/socialcast/devise_oauth2_providable/pull/17
