### ISSUE TITLE
Protected Resource Helpers?

### ISSUE THREAD

**Issue by pjammer** [socialcast/devise_oauth2_providable#2]
I know it may be outside of what you want to offer here, but actually i think it fits nicely.

similar to authenticate_user, there should be a method to protect a Controller resource where you need  an access token to trigger it.

I can create it in a fork, but what do you call your request.env[".....????..."]  I'll dig around, but if you know off the top of your head, cool.

**Comment by pjammer** [comment]
Half stealing from the same guy you borrowed from, We can do this quick and dirty using a  before_filter:

``` ruby
class UserInfoController < ApplicationController
  before_filter :require_oauth_token
  def index
    info = @current_token.user
    render :json => info.as_json()
  end
  protected
    def require_oauth_token
      @current_token = AccessToken.find_by_token(request.env["HTTP_AUTHORIZATION"].gsub(/OAuth /, ''))
      raise Rack::OAuth2::Server::Resource::Bearer::Unauthorized unless @current_token
    end
end
```

The one area i don't know how to adapt to your gem is getting the Header info, in a succinct way.  Does this `req.env` standardize the `AUTHORIZATION` header for us?  I think we should, since this is devise, scope it from a `current_user.access_token` perspective maybe?  Since this method is made to be used for when the guy is still logged into the provider app.

Thoughts?

**Comment by wireframe** [comment]
closing this out.  please reopen if you have a pull request for review.
