### ISSUE TITLE
Don't know how to build task 'devise_oauth2_providable:install:migrations'

### ISSUE THREAD

**Issue by roganartu** [socialcast/devise_oauth2_providable#20]
Followed instructions in README. Added to gemfile, then ran bundle install, then rake task and got error:

```
rake devise_oauth2_providable:install:migrations
rake aborted!
Don't know how to build task 'devise_oauth2_providable:install:migrations'
```

Using bundle exec rake ... doesn't make a difference. Neither does installing the gem using sudo gem install ...

Happy to post whatever you need and help work out what the issue is, but not sure where to start looking.

Running devise 1.4.8 and devise_oauth2_providable 0.3.8.

**Comment by wireframe** [comment]
the installation instructions are for the current 1.0.0.beta1 version.  for
the 0.3.8 installation instructions, you'll have to review the README from
the 0.3.8 tagged branch.

On Mon, Oct 17, 2011 at 11:54 AM, roganartu <
reply@reply.github.com>wrote:

> Followed instructions in README. Added to gemfile, then ran bundle install,
> then rake task and got error:
> 
>    rake devise_oauth2_providable:install:migrations
>    rake aborted!
>    Don't know how to build task
> 'devise_oauth2_providable:install:migrations'
> 
> Using bundle exec rake ... doesn't make a difference. Neither does
> installing the gem using sudo gem install ...
> 
> Happy to post whatever you need and help work out what the issue is, but
> not sure where to start looking.
> 
> Running devise 1.4.8 and devise_oauth2_providable 0.3.8.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/socialcast/devise_oauth2_providable/issues/20

## 
- Ryan Sonnek
- twitter: twitter.com/wireframe6464
- phone: 949.351.7290
