### ISSUE TITLE
rack-oauth2 gem version

### ISSUE THREAD

**Issue by matiaskorhonen** [socialcast/devise_oauth2_providable#8]
Is there a reason why **devise_oauth2_providable** depends on such an old version of [rack-oauth2](https://rubygems.org/gems/rack-oauth2)?

The current version of rack-oauth2 is 0.8.4 and the ~> 0.6.0 dependecy is causing a dependency conflict for me in a project I'm working on (fb_graph requires rack-oauth2 ~> 0.8.0).

```
Bundler could not find compatible versions for gem "rack-oauth2":
  In Gemfile:
    devise_oauth2_providable depends on
      rack-oauth2 (~> 0.6.3)

    fb_graph depends on
      rack-oauth2 (0.8.1)
```

**Comment by wireframe** [comment]
I'm open to upgrading to the latest version, but there is an api break
between 0.6 and 0.8 that needs to be resolved before i can release.

patches are always welcome.

On Mon, Jul 18, 2011 at 8:12 AM, k33l0r <
reply@reply.github.com>wrote:

> Is there a reason why **devise_oauth2_providable** depends on such an old
> version of [rack-oauth2](https://rubygems.org/gems/rack-oauth2)?
> 
> The current version of rack-oauth2 is 0.8.4 and the ~> 0.6.0 dependecy is
> causing a dependency conflict for me in a project I'm working on (fb_graph
> requires rack-oauth2 ~> 0.8.0).
> 
>    Bundler could not find compatible versions for gem "rack-oauth2":
>      In Gemfile:
>        devise_oauth2_providable depends on
>          rack-oauth2 (~> 0.6.3)
> 
> ```
>    fb_graph depends on
>      rack-oauth2 (0.8.1)
> ```
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/socialcast/devise_oauth2_providable/issues/8

## 
- Ryan Sonnek
- twitter: twitter.com/wireframe6464
- phone: 949.351.7290

**Comment by matiaskorhonen** [comment]
I started to look at it today (only needed to make one change so far) and I'll try and see if anything else needs to be done tomorrow.

**Comment by matiaskorhonen** [comment]
I actually managed to look into the matter just now and I have all the specs passing on REE, 1.8.7 and 1.9.2.

I submitted a pull request for the changes I made (#9).

**Comment by wireframe** [comment]
packaged changes into v0.3.7 release
